### ISSUE TITLE
Add a pkgconfig file

### ISSUE THREAD

**Issue by hobbitalastair** [JuliaStrings/utf8proc#105]
The netsurf project [uses](http://source.netsurf-browser.org/netsurf.git/tree/Makefile#n532) a [pkgconfig file](http://source.netsurf-browser.org/libutf8proc.git/tree/libutf8proc.pc.in) to find linking flags for utf8proc. It would be nice to have this in the upstream library.

@tlsa this seems to be required to build against upstream instead of netsurf's fork.

**Comment by stevengj** [comment]
Seems reasonable to add.

**Comment by ianwlarson** [comment]
[utf8proc.txt](https://github.com/JuliaLang/utf8proc/files/1123089/utf8proc.txt)

Very straightforward to make.

**Comment by ianwlarson** [comment]
#108

**Comment by stevengj** [comment]
CLosed by #142.
