### ISSUE TITLE
Compilation on windows

### ISSUE THREAD

**Issue by SteelCrow** [JuliaStrings/utf8proc#109]
Hi, guys!

Need some help, try to compile lib on win 7.
Use _**cmake ../ -G"Visual Studio 15 Win64"**_ to create project for msvs.
Then **_build solution in msvs with Release configuration_**  and in folder see only _.lib_ file.
As far as I know to use library on win I need three files _.h_ _.lib_ and _.dll_, is it right?
I link static lib and add header to my project, but as expected get external symbol __imp... error.
How to compile this lib with .dll on win? I try many ways to do it but without success...
Is it nessesary to have .lib if I want to use .dll? Is there any way to use only static .lib or for that I need to modify .h?

Sorry for noobs question, but I really confused with such situation.

**Comment by Thomas-Haase** [comment]
I'm using Visual Studio 2017 (Version 15.2). Same effect here. Building is successful without errors, but I expect to see _dll_ files, but I get _lib_ files. The source code is using `UTF8PROC_EXPORTS` to use the Microsoft `__declspec(dllexport)` technique, which seems to indicate clearly that the target file should be a _dll_ and not a static `lib`. Also, when building on Linux, the target is a dynamic library with extension _so_. So probably, some setting in `CMakeLists.txt` is wrong?

**Comment by Blonder** [comment]
I added an option to the CMakeLists.txt file to select to build a static or dynamic libraray, see pull request #111

**Comment by stevengj** [comment]
Just build with `BUILD_SHARED_LIBS=true`
