### ISSUE TITLE
Possible miscategorization for east Asian numerals

### ISSUE THREAD

**Issue by ararslan** [JuliaStrings/utf8proc#126]
Is it expected that `四` (Japanese 4) is identified as having category "Lo: Letter, other" rather than, for example, "Nl: Number, letter"? It seems that all Japanese numerals with the exception of 0 (`〇`) are categorized as Lo, whereas `〇` is Nl.

**Comment by ararslan** [comment]
As a data point, note that Wikipedia's page for [numbers in Unicode](https://en.wikipedia.org/wiki/Numerals_in_Unicode) gives 六 as an example along with numbers in Tamil, Devanagari, etc. Of the examples given in the first table on that page, only 六 fails to be identified as a number.

**Comment by JeffBezanson** [comment]
These characters don't have individual entries in UnicodeData but are grouped together:

```
4E00;<CJK Ideograph, First>;Lo;0;L;;;;;N;;;;;
9FD5;<CJK Ideograph, Last>;Lo;0;L;;;;;N;;;;;
```

According to that they are `Lo`, and https://www.unicode.org/Public/10.0.0/ucd/extracted/DerivedNumericType.txt also agrees. I don't know whether there might be more to the story though.

**Comment by stevengj** [comment]
Other sources like https://www.compart.com/en/unicode/U+56DB also list it as Lo, too.  Seem like we are doing the right thing here.
