### ISSUE TITLE
Documentation gone awol.

### ISSUE THREAD

**Issue by original-birdman** [JuliaStrings/utf8proc#139]
There used to be some additional API documentation at 
        https://julialang.org/utf8proc/doc/
but this is no longer there.

Could it be made ot re-appear somewhere?

**Comment by stevengj** [comment]
It is still available at http://juliastrings.github.io/utf8proc/ … the redirect from the julialang.org site seems broken (https://github.com/JuliaLang/julialang.github.com/issues/809)

**Comment by original-birdman** [comment]
Thanks.
