### ISSUE TITLE
"Policy CMP0042 is not set" warning on macOS

### ISSUE THREAD

**Issue by jakirkham** [JuliaStrings/utf8proc#145]
Seeing the following warning when building `utf8proc` with CMake on macOS.

```
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   utf8proc
```

**Comment by stevengj** [comment]
This warning is innocuous, but it wouldn't hurt to add a `set(CMAKE_MACOSX_RPATH On)` line somewhere to silence this.

**Comment by dundargoc** [comment]
This is fixed.

**Comment by dundargoc** [comment]
Pretty sure this has been fixed as the minimum version has been bumped.

**Comment by stevengj** [comment]
Yes, it looks like `CMAKE_MACOSX_RPATH` now defaults to `true` in `cmake` version 3.0 or later (we require 3.5).
