### ISSUE TITLE
utf8proc.h comments provides outdated information

### ISSUE THREAD

**Issue by Thomas-Haase** [JuliaStrings/utf8proc#157]
- copyright should use 2019 instead of 2018?
- Unicode version 9.0.0. is mentioned. It should be 12.1 ?
- copyright in this header file does not match content of LICENCE.MD.

**Comment by stevengj** [comment]
Thanks, I updated the comments.

The copyright year is not too critical, anyway.   The license statement for the header file applies specifically to the contents of that file, so it doesn't need to mention the Unicode Data License (which applies to `utf8proc_data.c`).
