### ISSUE TITLE
makefile generates old version 2.3.1 filename

### ISSUE THREAD

**Issue by Thomas-Haase** [JuliaStrings/utf8proc#162]
The makefile still uses 2.3.1 as file name suffix instead of 2.4.0. This is confusing
makefile:
```txt
MAJOR=2
MINOR=3
PATCH=1
```
utf8proc.h:
```cpp
/** The MAJOR version number (increased when backwards API compatibility is broken). */
#define UTF8PROC_VERSION_MAJOR 2
/** The MINOR version number (increased when new functionality is added in a backwards-compatible manner). */
#define UTF8PROC_VERSION_MINOR 4
/** The PATCH version (increased for fixes that do not change the API). */
#define UTF8PROC_VERSION_PATCH 0
```

**Comment by stevengj** [comment]
Actually, it's not a bug.   The version number in the Makefile is for the ABI and indicates binary compatibility, whereas the version number of the package is for the API and package.  The two don't need to match — in the case of utf8proc 2.4 we updated the package version but it remained backward-compatible on a binary level.
