### ISSUE TITLE
Zerowidth reported for some width=1 characters

### ISSUE THREAD

**Issue by original-birdman** [JuliaStrings/utf8proc#167]
This is for version 2.3 and 2.4.

U+00A8 (diaresis) and  U+00B4 (acute accent) now both return 0 in a `utf8proc_charwidth()` call.
At some point in the past they returned 1 (according to an old log output I have).

The result _should_ be 1. These are _not_ combining diacriticals, but are "spacing characters", (just as U+00af - macron and U+00b0 - degree sign are). They are what you use if you want a "bare" diaresis or acute.

(The combining diacritics are U+0308 and U+0301 respectively).

**Comment by stevengj** [comment]
Good catch.  Right now we assign zero width to everything in category Sk (Symbol, modifier), which doesn't seem right.   But it looks like some of the characters in that category are zero width (e.g. [U+1F3FB](https://www.fileformat.info/info/unicode/char/1f3fb/index.htm)), so it's unclear to me what rule we should use in general.

**Comment by original-birdman** [comment]
> Good catch. 

It just happened to be in my one-line test file.

> But it looks like some of the characters in that category are zero width (e.g. [U+1F3FB](https://www.fileformat.info/info/unicode/char/1f3fb/index.htm)), so it's unclear to me what rule we should use in general.

Oddly, Unicode declares that character to be Wide (in the `EastAsianWidth.txt` defs)!

```
1F3FB..1F3FF;W   # Sk     [5] EMOJI MODIFIER FITZPATRICK TYPE-1-2..EMOJI MODIFI$
```

**Comment by stevengj** [comment]
Hmm, according to http://unicode.org/reports/tr51/, whether the emoji skin-tone characters are zero-width combining characters depends on the font.  So I guess in a fixed-width font they are wide, not combining.

If this is true of everything in Sk, that makes life easy — we just remove them from the set of zero-width combining characters [here](https://github.com/JuliaStrings/utf8proc/blob/20672dba69bf463be22f6c9c216d858c9d116bb6/data/charwidths.jl#L63).
