### ISSUE TITLE
Implicit signedness conversion warnings

### ISSUE THREAD

**Issue by gregwillits** [JuliaStrings/utf8proc#169]
There are a couple dozen places where there are implicit changes to signedness. I suspect there are many people who don't have that warning on, but it's an important detail to code I work on.

Would be nice if either the differences in signedness were eliminated, or at least made explicit with casting when necessary. The warnings make for a noisy list which has to be mentally checked, filtered, and ignored, when looking for my own code's warnings.

To me some look obvious enough to correct (declaring two variables with one as int and one as uint then later comparing them), but others look more subtle. Normally I go through and fix these things, but I'm too new to this library (and UTF-8 management) to understand the ramifications of many of them--and where the correct place is to address the signedness.

**Comment by stevengj** [comment]
Sure, a PR eliminating any of these would be welcome.

**Comment by stevengj** [comment]
Fixed by #214.
