### ISSUE TITLE
utf8proc_charwidth returns 1 for é character

### ISSUE THREAD

**Issue by markand** [JuliaStrings/utf8proc#170]
Hi,

I'm sorry if I misunderstood the purpose of utf8proc_charwidth, I thought it'd return the number of bytes required for a given codepoint.

Example, the letter é in UTF-8 is two bytes long (value of 233 in unicode) but `utf8proc_charwidth(233)` always return 1.

Did I miss something or there is no function to get the number of bytes a codepoint require?

**Comment by PallHaraldsson** [comment]
I think you have this in mind:

```
julia> ncodeunits("é")
2
```

I think the other has to do with with on the screen, if I recall to support Chinese.

**Comment by stevengj** [comment]
charwidth is an approximate on-screen width in fixed-width fonts, not the number of code units.
