### ISSUE TITLE
Is it intended that the tests are missing in the CMakeLists.txt?

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [JuliaStrings/utf8proc#171]

**Comment by stevengj** [comment]
We primarily use the `Makefile` for development.  `CMakeLists.txt` is only to simplify installation for Windows users.

**Comment by Andreas-Schniertshauer** [comment]
I added the following to the CMakeLists.txt file:
`
if(UTF8PROC_ENABLE_TESTING)
  enable_testing()
  add_executable(case test/tests.h test/tests.c utf8proc.h test/case.c)
  target_link_libraries(case utf8proc)
  add_executable(charwidth test/tests.h test/tests.c utf8proc.h test/charwidth.c)
  target_link_libraries(charwidth utf8proc)
  add_executable(custom test/tests.h test/tests.c utf8proc.h test/custom.c)
  target_link_libraries(custom utf8proc)
  add_executable(graphemetest test/tests.h test/tests.c utf8proc.h test/graphemetest.c)
  target_link_libraries(graphemetest utf8proc)
  add_executable(iterate test/tests.h test/tests.c utf8proc.h test/iterate.c)
  target_link_libraries(iterate utf8proc)
  add_executable(misc test/tests.h test/tests.c utf8proc.h test/misc.c)
  target_link_libraries(misc utf8proc)
  add_executable(normtest test/tests.h test/tests.c utf8proc.h test/normtest.c)
  target_link_libraries(normtest utf8proc)
  add_executable(printproperty test/tests.h test/tests.c utf8proc.h test/printproperty.c)
  target_link_libraries(printproperty utf8proc)
  add_executable(valid test/tests.h test/tests.c utf8proc.h test/valid.c)
  target_link_libraries(valid utf8proc)
  add_test(testcase case)
  add_test(testcustom custom)
  add_test(testiterate iterate)
  add_test(testmisc misc)
  add_test(testprintproperty printproperty)
  add_test(testvalid valid)
endif()
`
Did not add testcharwidth, testgraphemetest and testnormtest because of compiler error on Windows missing getline and wcwidth.

**Comment by stevengj** [comment]
Those warnings are innocuous, I believe. A PR that adds tests to the cmake script would be welcomed. We would also welcome a PR with some type casts that silence the conversion warnings in the tests.

**Comment by Andreas-Schniertshauer** [comment]
I added the tests see #173
