### ISSUE TITLE
normtest and graphemetest would compile on Windows with the following mygetline implementation found on stackoverflow

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [JuliaStrings/utf8proc#182]
`
#ifdef _MSC_VER
/*
  https://stackoverflow.com/questions/735126/are-there-alternate-implementations-of-gnu-getline-interface/735472#735472
  if typedef doesn't exist (msvc, blah)
*/
typedef intptr_t ssize_t;
ssize_t mygetline(char **lineptr, size_t *n, FILE *stream) {
    size_t pos;
    int c;

    if (lineptr == NULL || stream == NULL || n == NULL) {
        errno = EINVAL;
        return -1;
    }

    c = getc(stream);
    if (c == EOF) {
        return -1;
    }

    if (*lineptr == NULL) {
        *lineptr = malloc(128);
        if (*lineptr == NULL) {
            return -1;
        }
        *n = 128;
    }

    pos = 0;
    while(c != EOF) {
        if (pos + 1 >= *n) {
            size_t new_size = *n + (*n >> 2);
            if (new_size < 128) {
                new_size = 128;
            }
            char *new_ptr = realloc(*lineptr, new_size);
            if (new_ptr == NULL) {
                return -1;
            }
            *n = new_size;
            *lineptr = new_ptr;
        }

        ((unsigned char *)(*lineptr))[pos ++] = c;
        if (c == '\n') {
            break;
        }
        c = getc(stream);
    }

    (*lineptr)[pos] = '\0';
    return pos;
}
#endif
`

**Comment by Andreas-Schniertshauer** [comment]
And using this implementation when compiling for Windows https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c
would solve the problem with wcwidth on Windows in the graphemetest.
![grafik](https://user-images.githubusercontent.com/59561559/77821481-ed0e0a80-70ea-11ea-8973-0b3c70ae2ccf.png)

**Comment by Andreas-Schniertshauer** [comment]
When executing graphemetest with GraphemeBreakTest.txt I run into an error in file tests\tests.c
`
size_t skipspaces(const char *buf, size_t i)
{
    while (isspace(buf[i])) ++i;
    return i;
}
`
because the first char in the string
`"Ã· 0020 Ã· 0020 Ã·\t#  Ã· [0.2] SPACE (Other) Ã· [999.0] SPACE (Other) Ã· [0.3]\n"`
is negative because of char to int conversion.
`0x000001F66FF56DC0  c3 b7 20 30 30 32 30 20 c3 b7 20 30 30 32 30 20 c3 b7 09  Ã· 0020 Ã· 0020 Ã·.
0x000001F66FF56DD3  23 20 20 c3 b7 20 5b 30 2e 32 5d 20 53 50 41 43 45 20 28  #  Ã· [0.2] SPACE (
0x000001F66FF56DE6  4f 74 68 65 72 29 20 c3 b7 20 5b 39 39 39 2e 30 5d 20 53  Other) Ã· [999.0] S
0x000001F66FF56DF9  50 41 43 45 20 28 4f 74 68 65 72 29 20 c3 b7 20 5b 30 2e  PACE (Other) Ã· [0.
0x000001F66FF56E0C  33 5d 0a 00 20 55 2e 53 2e 20 61 6e 64 20 6f 74 68 65 72  3].. U.S. and other
0x000001F66FF56E1F  20 63 6f 75 6e 74 72 69 65 73 2e 0a 00`

**Comment by stevengj** [comment]
Code on StackOverflow is CC-BY-SA by default (https://stackoverflow.com/help/licensing).  That post includes a line "This code is public domain", but unfortunately that is not a precise legal phrase and hence is unusable — this is the usual problem with non-lawyers writing their own licenses.  (To see how hard it is to write a true public-domain declaration, see [the CC0 license](https://creativecommons.org/share-your-work/public-domain/cc0).)

So, we can't use that code, sorry.

**Comment by stevengj** [comment]
I just committed a simplistic getline replacement that is sufficient for our purposes.  (Since we only need to read the Unicode test files, we can bound the line length and omit the error checking.)
