### ISSUE TITLE
Add build and Testing folders to .gitignore?

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [JuliaStrings/utf8proc#185]
Can we add the build directory and Testing folder to the .gitignore list?
In TortoiseGit is is very annoying when checking for modifications:
![grafik](https://user-images.githubusercontent.com/59561559/77834929-cd0d3400-7148-11ea-8323-8d72d5f9bb81.png)
Can we also change the appveyor.yml to generate the code to build\msvc_shared, build\msvc_static, build/mingw_static and build/mingw_shared? To be more consistent, to get rid of all builds in one rm -rf build, to get rid of 
![grafik](https://user-images.githubusercontent.com/59561559/77835021-badfc580-7149-11ea-8ffd-29641d2996ed.png)
and to get rid of displaying alle files from these folders and subfolder when checking for modifications in TortoiseGit.
Thanks.

**Comment by stevengj** [comment]
I guess `build` is a semi-standard for the directory that you build cmake projects in (although in principle this is arbitrary), so I'm fine with adding that to `.gitignore`.

But what creates the `Testing` directory for you?  I don't get this when I run `cmake` or `ctest`.

**Comment by Andreas-Schniertshauer** [comment]
I'll look at the Tesing dir, don't know who creates it, contains a temp dir and a LastTest.log and a CTestCostData.txt file.

**Comment by Andreas-Schniertshauer** [comment]
Seems to be an accident on my side, maybe I called cmake/ctest in the root and not in the build dir, sorry.
