### ISSUE TITLE
D port of the library

### ISSUE THREAD

**Issue by aferust** [JuliaStrings/utf8proc#191]
Hi the authors of the library,

I ported / translated the library to dlang.
https://github.com/aferust/utf8proc-d

I included your license file in the port, and explicitly included the name of the original authors in dub.json file. Hope, I neither violate any copyright nor made you angry. 
Please let me knöw if you want me to do möre.

Best regards!

**Comment by stevengj** [comment]
Thanks!

Why port the code, as opposed to just [calling the C library from D](https://dlang.org/spec/interfaceToC.html)?

**Comment by aferust** [comment]
Yes, it is easy to call c functions in d. But that require c linkage and a c compiler (not a big deal though). Bindings work too. But, I like to promote dlang in terms of emphasizing its capabilities.

**Comment by stevengj** [comment]
Sure, I understand.
