### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by xkszltl** [JuliaStrings/utf8proc#192]
These 2 files are downloaded for unit tests.
https://github.com/JuliaStrings/utf8proc/blob/b5211c88af605c4572f72c1ed103e834aa0e7618/CMakeLists.txt#L68-L69

Since server support https, should we use that instead?
In case you want to support cmake built without openssl, maybe we can have an option to decide the prefix.
Also, if https is used, recommend to expose `CMAKE_TLS_VERIFY` as an option and default to `ON`.

**Comment by stevengj** [comment]
Sure, can you file a PR to use https in CMakeLists and the Makefiles?

**Comment by xkszltl** [comment]
OK, will find a time slot for it.

**Comment by xkszltl** [comment]
Before I move forward, could you clarify if you were intentionally keeping compatibility for edge cases like special cmake without openssl?
If not I can simply add a `s`.

**Comment by stevengj** [comment]
No, just add an `s`.
