### ISSUE TITLE
Undefined character listed as UTF8PROC_CATEGORY_LO

### ISSUE THREAD

**Issue by maartenbreddels** [JuliaStrings/utf8proc#194]
Hi all,

I found in https://github.com/apache/arrow/pull/7656 that undefine characters (such as https://www.compart.com/en/unicode/U+08BE) are listed as UTF8PROC_CATEGORY_LO (using `utf8proc_category`). Could this be a bug? 

Regards,

Maarten

**Comment by stevengj** [comment]
[U+08BE](https://www.fileformat.info/info/unicode/char/08be/index.htm) was defined in Unicode 13, and Lo is correct.

**Comment by stevengj** [comment]
(It correctly returns `UTF8PROC_CATEGORY_CN` for unassigned codepoints like [U+0378](https://www.fileformat.info/info/unicode/char/0378/index.htm).)

**Comment by maartenbreddels** [comment]
You are correct, it didn't even cross my mind that Unicode changes that fast (apart from emoticons), thanks!
