### ISSUE TITLE
Include case information from DerivedCoreProperties.txt

### ISSUE THREAD

**Issue by maartenbreddels** [JuliaStrings/utf8proc#195]
Hi,

Roman letter Ⅰ to Ⅿ and circled letters Ⓐ to Ⓩ are upper case characters, which should be listed in DerivedCoreProperties.txt, and many more for lower case codepoints. Are there plans to include this information?

Regards,

Maarten

ref: https://github.com/apache/arrow/pull/7656

**Comment by stevengj** [comment]
A simple workaround seems like it would be `isupper(c) = uppercase(c) == c && lowercase(c) != c` , and conversely for `islower`… is there an application where this would not be sufficient?

It seems like anything that needed something fancier than that would need locale information etcetera too…

**Comment by maartenbreddels** [comment]
I assumed it didn't work (reading throught the unicode spec), but for upper case testing it does actually:
```c++
  return (HasAnyUnicodeGeneralCategory(codepoint, UTF8PROC_CATEGORY_LU) ||
          ((static_cast<uint32_t>(utf8proc_toupper(codepoint)) == codepoint) &&
           (static_cast<uint32_t>(utf8proc_tolower(codepoint)) != codepoint))) &&
         !HasAnyUnicodeGeneralCategory(codepoint, UTF8PROC_CATEGORY_LT);
```

I think that's more out of luck, the equivalent for lower casing doesn't work, one example is U+00AA, which is listed as lower case, but has no upper case version. https://graphemica.com/%C2%AA

I think locale information is a step too far indeed. Do you think storing if something is lower or upper case is out of scope for utf8proc?

**Comment by stevengj** [comment]
What is the application of knowing whether U+00AA is lower case?

**Comment by stevengj** [comment]
For example, if you're trying to detect proper nouns in text, then characters like U+00AA without an upper-case version are not a concern.  (Moreover, no locale-unaware test for a proper noun seems likely to be completely reliable.)

**Comment by maartenbreddels** [comment]
I am translating Python semantics to Apache Arrow. Pandas dataframes use Python for string manipulations, to get better performance, like [str.islower()](https://docs.python.org/3/library/stdtypes.html#str.islower). So it's not that I have a use case in mind now, but it would be easier to explain if we have no exceptions.

So, it's not that I have a use case in mind next, but a lot of data scientists will rely on this code, having to explain less, and being conformant to a spec (if I am not mistaken) is a big +.

**Comment by stevengj** [comment]
That's reasonable.

We can probably store this information without changing our data structure just by storing sentinel values in  the `uppercase_seqindex` and `utf8proc_uint16_t lowercase_seqindex` …
