### ISSUE TITLE
Suggest the maximum limit of a valid text string

### ISSUE THREAD

**Issue by ambarj2009** [JuliaStrings/utf8proc#199]
Hello guys

Values like the following are currently being used to limit the largest supported text string (in the source code of the utf8proc_decompose_custom function):

(utf8proc_ssize_t) (SSIZE_MAX / sizeof (utf8proc_int32_t) / 2)

This value is being iterated, when in reality it is always the same in all iterations: Why don't you pre-calculate it and use that already calculated value instead of doing it every time?

I would at least suggest being able to set this value via a configuration parameter or something similar, so that anyone using this library can set the limit to a value closer to their needs.

Thanks for your work, utf8proc is a great library.

Best regards

**Comment by stevengj** [comment]
The compiler should be able to constant-fold this, so that it is not actually computed at runtime.

The maximum here is set by the size of addresses on your machine (32-bit or 64-bit), so it is not something that can be set by the user.
