### ISSUE TITLE
Grapheme breaks

### ISSUE THREAD

**Issue by gerald-brandt** [JuliaStrings/utf8proc#203]
Grapheme breaks seem to be wrong. The sequence ಇಲ್ಲಿ should be two graphemes, yet utf8proc sees it as three 
![image](https://user-images.githubusercontent.com/11981161/99014936-65f69100-2519-11eb-8489-c4d80e781821.png)

**Comment by archermarx** [comment]
There are also some issues with emoji grapheme breaks. 👨🏻‍🤝‍👨🏽 is broken up as [👨🏻\u200d] and 🇸🇪🇸🇪 is broken into [🇸🇪🇸, 
 🇪]

**Comment by stevengj** [comment]
See #204.

**Comment by gerald-brandt** [comment]
This needs reopening. Although the fix may solve archermarx's comment, it doesn't solve the original issue.  Latest trunk still gives: 
![image](https://user-images.githubusercontent.com/11981161/100011401-48d28580-2d97-11eb-807c-6fdf18ce5498.png)

**Comment by stevengj** [comment]
`"ಇಲ್ಲಿ"` consists of 5 codepoints:
```jl
julia> collect("ಇಲ್ಲಿ")
5-element Array{Char,1}:
 'ಇ': Unicode U+0C87 (category Lo: Letter, other)
 'ಲ': Unicode U+0CB2 (category Lo: Letter, other)
 '್': Unicode U+0CCD (category Mn: Mark, nonspacing)
 'ಲ': Unicode U+0CB2 (category Lo: Letter, other)
 'ಿ': Unicode U+0CBF (category Mn: Mark, nonspacing)
```
These have [Grapheme_Cluster_Break property values](http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Break_Property_Values) ANY, ANY, EXTEND, ANY, and EXTEND, respectively, according to our data tables.     So, if I'm reading [UAX#29](http://www.unicode.org/reports/tr29/) correctly, it *should* be three graphemes.  What am I missing?

**Comment by stevengj** [comment]
The Python [`grapheme` package](https://pypi.org/project/grapheme/) (version 0.6 in Python 3.9) agrees:
```py
>>> import grapheme
>>> grapheme.length("ಇಲ್ಲಿ")
3
```

**Comment by gerald-brandt** [comment]
It's possible I'm misunderstanding, but I'm basing my observations after http://kermitproject.org/utf8.html which displays The first line of Kannada poetry as:
![image](https://user-images.githubusercontent.com/11981161/100015094-02802500-2d9d-11eb-97da-e3714636537b.png)

while utf8proc using grapheme boundaries displays it as:
![image](https://user-images.githubusercontent.com/11981161/100015186-29d6f200-2d9d-11eb-84ca-911319310944.png)

There are definite difference between the two, which I though were grapheme issues.

**Comment by stevengj** [comment]
I think you are seeing font ligatures, which can combine characters in ways independent of Unicode graphemes.

**Comment by gerald-brandt** [comment]
In that case, I don't know how to display ಲ್ಲಿ properly using utf8proc. Instead of displaying a grapheme at a time, do I need to see if the grapheme separator is Category Mn and treat the entire sequence 
 'ಲ': Unicode U+0CB2 (category Lo: Letter, other)
 '್': Unicode U+0CCD (category Mn: Mark, nonspacing)
 'ಲ': Unicode U+0CB2 (category Lo: Letter, other)
 'ಿ': Unicode U+0CBF (category Mn: Mark, nonspacing)
as a single displayable piece?

**Comment by stevengj** [comment]
I'm not sure what you mean by "display using utf8proc".   utf8proc knows nothing about "display" (i.e. fonts and text rendering).

In general, text-rendering systems can arbitrarily combine characters into glyphs depending on the font, so rendering one grapheme at a time might not match how the combined text is rendered.

If you really need this level of information, you will need to query the font rendering system. [HarfBuzz](https://en.wikipedia.org/wiki/HarfBuzz) is a good open-source alternative here.

**Comment by gerald-brandt** [comment]
I understand utf8proc does nothing with display. I'm just trying to figure out how to pass the  grapheme group to the render system so it knows what to do with the graphemes.

If I use utf8proc to find grapheme boundaries, and make sure that boundary isn't a UTF8PROC_BOUNDCLASS_EXTEND, then I can clump graphemes into what should be (to the rendering system) a single displayable piece.

Thanks for your help... this doesn't seem to be an issue with utf8proc's grapheme boundary code.
