### ISSUE TITLE
2.6.1: tests are not off-source tee ready

### ISSUE THREAD

**Issue by kloczek** [JuliaStrings/utf8proc#212]
When source tree is configured with `cmake -B <build_dir>` and tests are executed over `make -C <build_dir> test` testing procedure fauils because hardcoded path to unicode files in `data/` in source tree.
More details in #207

**Comment by stevengj** [comment]
More precisely
```sh
cmake -DUTF8PROC_ENABLE_TESTING=On -B build
make -C build
make -C build test
```
gives
```
The following tests FAILED:
	  8 - utf8proc.testgraphemetest (Failed)
	  9 - utf8proc.testnormtest (Failed)
```
Note that
```sh
mkdir build
cd build
cmake -DUTF8PROC_ENABLE_TESTING=On ..
make
make test
```
works, however.

**Comment by kloczek** [comment]
You are not using in paths variables pointing to source tree path.

**Comment by stevengj** [comment]
If you have additional changes to suggest, a PR would be welcome.
