### ISSUE TITLE
Hangul decomposition does not work?

### ISSUE THREAD

**Issue by vadim-berman** [JuliaStrings/utf8proc#217]
Hello Utf8proc team,

I am trying to use utf8proc to decompose Korean text to either NFD or NFKD form. I tried using `utf8proc_decompose` and `utf8proc_NFKD`. The result is that the original string is returned. What am I doing wrong? 

Source code is like this:
```
    static void *buf = nullptr;
    const auto options = (utf8proc_option_t)(UTF8PROC_NULLTERM|UTF8PROC_STABLE|UTF8PROC_DECOMPOSE);
...
    result = utf8proc_decompose((uint8_t*)s,0, (int32_t*)buf,result, options);
```

Example input: `u8"블랙"`

**Comment by stevengj** [comment]
I just checked this in Julia (which calls utf8proc for string normalization), and `"블랙"` (2 codepoints) with NFD normalization indeed gets normalized to `"블랙"` (6 codepoints: U+1107 U+1173 U+11AF U+1105 U+1162 U+11A8).

Of course, the strings *look* the same when printed, but that is always true of canonically equivalent strings.

**Comment by vadim-berman** [comment]
Thank you, @stevengj. 

I want to be able to apply regexes (re2 library) matching the constituents of the syllable. For example, I want `랙` to match a regex like `.+ㄱ`. Meaning, I expect one of these functions to convert `랙` to `ㄹㅏㄱ`.

Can it be done?

**Comment by stevengj** [comment]
I don't know anything about the Hangul script, but it doesn't seem that `"ㄹㅏㄱ"` (U+3139 U+314F U+3131)is produced by the NFD decomposition of `"블랙"` (which gives the characters I listed above).  You probably need a language-specific tool.

**Comment by vadim-berman** [comment]
It's the last character, not the entire string. Sorry, the middle character is off, but you got the idea. 

Take a look at [this thread in Stackoverflow](https://stackoverflow.com/questions/41309402/breaking-down-a-hangul-syllable-into-letters-jamo), @stevengj. If the Java decomposition produces these characters, shouldn't utf8proc do so too?

In fact, it's one of the most frequent use cases for decomposition / composition.

**Comment by vadim-berman** [comment]
Actually, my mistake. The last character is supposed to be `ㄱ` rather than `ㄱ`. They look the same but they are different. 

Doesn't matter though. I built my own tiny function, based on `tiny_utf8`. Thanks, I guess.

**Comment by stevengj** [comment]
The example given on the StackOverflow page is `퓛` (U+D4DB) → `ᄑ` (U+1111) + `ᅱ` (U+1171) + `ᆶ` (U+11B6), and this is correctly reproduced by utf8proc:
```jl
julia> using Unicode

julia> collect(Unicode.normalize("퓛", :NFD))
3-element Array{Char,1}:
 'ᄑ': Unicode U+1111 (category Lo: Letter, other)
 'ᅱ': Unicode U+1171 (category Lo: Letter, other)
 'ᆶ': Unicode U+11B6 (category Lo: Letter, other)
```

**Comment by stevengj** [comment]
The string `"블랙"` also gets decomposed by utf8proc and indeed ends with `ᆨ` (U+11A8):
```jl
julia> collect(Unicode.normalize("블랙", :NFD))
6-element Array{Char,1}:
 'ᄇ': Unicode U+1107 (category Lo: Letter, other)
 'ᅳ': Unicode U+1173 (category Lo: Letter, other)
 'ᆯ': Unicode U+11AF (category Lo: Letter, other)
 'ᄅ': Unicode U+1105 (category Lo: Letter, other)
 'ᅢ': Unicode U+1162 (category Lo: Letter, other)
 'ᆨ': Unicode U+11A8 (category Lo: Letter, other)
```
