### ISSUE TITLE
cmake instructions reference make

### ISSUE THREAD

**Issue by ryanpcmcquen** [JuliaStrings/utf8proc#236]
On the README, the `cmake` instructions are as follows:

Alternatively, you can compile with cmake, e.g. by
```
mkdir build
cd build
cmake ..
make
```

But on Windows `make` won't be available. Is the last `make` just a typo?

**Comment by inkydragon** [comment]
> Is the last make just a typo?

It does look like a typo.

----

These steps work well for both `*.nix` and win.

https://github.com/JuliaStrings/utf8proc/blob/2484e2ed5e1d9c19edcccf392a7d9920ad90dfaf/.github/workflows/cmake.yml#L23-L27

Without test:
```sh
mkdir build
cmake -S . -B build
cmake --build build
```

And for MinGW
https://github.com/JuliaStrings/utf8proc/blob/2484e2ed5e1d9c19edcccf392a7d9920ad90dfaf/.github/workflows/cmake.yml#L54-L58

**Comment by stevengj** [comment]
Updated to use
```sh
mkdir build
cmake -S . -B build
cmake --build build
```
