### ISSUE TITLE
undefined reference to `__imp_utf8proc_encode_char'

### ISSUE THREAD

**Issue by Clownsw** [JuliaStrings/utf8proc#243]
gcc main.c -o main.exe -IC:\Users\s's\Desktop\utf8proc -LC:\Users\s's\Desktop\utf8proc\build -lutf8proc

d:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\s's\AppData\Local\Temp\ccqT94lv.o:main.c:(.text+0x24): undefined reference to `__imp_utf8proc_encode_char'
collect2.exe: error: ld returned 1 exit status

**Comment by stevengj** [comment]
How did you build utf8proc?  With cmake, or with the makefile and mingw?

**Comment by Clownsw** [comment]
> How did you build utf8proc? With cmake, or with the makefile and mingw?

windows mingw

**Comment by stevengj** [comment]
You need to make sure to include `-DUTF8PROC_EXPORTS` in the compiler flags when compiling on Windows.    If you use `cmake`, this is done automatically, but with mingw you will probably have to do something like:
```sh
make CPPFLAGS="-DUTF8PROC_EXPORTS"
```
We could probably add a `Makefile` rule to do this automatically [here](https://github.com/JuliaStrings/utf8proc/blob/63f31c908ef7656415f73d6c178f08181239f74c/Makefile#L29-L36); feel free to contribute a PR.

**Comment by Clownsw** [comment]
> ```shell
> ```shell
> make CPPFLAGS="-DUTF8PROC_EXPORTS"
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

thanks
