### ISSUE TITLE
Consider using release assets

### ISSUE THREAD

**Issue by diizzyy** [JuliaStrings/utf8proc#251]
Earlier this year GitHub announced that generated source archives are only stable for a year, this will likely cause major issues for anyone trying to package utf8proc longterm. Please consider uploading release source code archives.

Reference:
https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by stevengj** [comment]
Thanks, for the latest release (2.9.0) I've attached a tarball as a release asset.
