### ISSUE TITLE
Enhancement Request: Custom Allocator Support in utf8proc

### ISSUE THREAD

**Issue by shakhvit** [JuliaStrings/utf8proc#256]
I've been using utf8proc and thought of a feature that could be quite handy: support for custom memory allocators. This would be especially useful in contexts like embedded systems or tight-memory environments, where precise control over memory operations is crucial.

A similar feature is found in the wolfSSL library, where custom `malloc`, `realloc`, and `free` functions can be set (e.g., through `wolfSSL_SetAllocators()`). Implementing this in utf8proc would really boost its adaptability for various specialized use cases.

I noticed that memory allocation and reallocation are currently used only in one function within utf8proc. Given this, adding custom allocator support seems like a straightforward task. I'm more than willing to contribute to this enhancement by implementing it and submitting a PR for the team's review.

Looking forward to any feedback or thoughts on this idea.

**Comment by stevengj** [comment]
In an embedded system with tight memory environments, wouldn't you simply compile utf8proc yourself, in which case you can use whatever allocator you want?  It's only one `.c` file, after all.

**Comment by shakhvit** [comment]
Ok, I'll do that. It just brings an additional overhead for merging upstream changes into my fork. I thought that these changes may be useful not only for me. But no problem, I'll deal with that. Thanks for your time.
