### ISSUE TITLE
normalization does not commute with case-folding?

### ISSUE THREAD

**Issue by stevengj** [JuliaStrings/utf8proc#257]
I noticed an odd case in https://github.com/JuliaLang/julia/issues/52408#issuecomment-1845561337:

```jl
julia> using Unicode: normalize

julia> s = "J\uf72\uec8\u345\u315\u5bf\u5bb\U1d16d\u5b0\u334\u35c"
"J"

julia> normalize(s, casefold=true) == normalize(normalize(s), casefold=true)
false

julia> normalize(normalize(s, casefold=true)) == normalize(normalize(s), casefold=true)
false
```
(The Julia `Unicode.normalize` function calls `utf8proc`, and defaults to NFC normalization.)

Not sure if this is a bug or just a weird behavior of Unicode.  Would be good to try it out with ICU or some other library.

**Comment by stevengj** [comment]
I get something similar in Python 3:
```py
>>> import unicodedata
>>> s = "J\u0f72\u0ec8\u0345\u0315\u05bf\u05bb\U0001d16d\u05b0\u0334\u035c"
>>> unicodedata.normalize("NFC", s.casefold()) == unicodedata.normalize("NFC", s).casefold()
>>> unicodedata.normalize("NFC", s.casefold()) == unicodedata.normalize("NFC", unicodedata.normalize("NFC", s).casefold())
```
So I guess this is a weird quirk of Unicode?
```

**Comment by StefanKarpinski** [comment]
That's quite unfortunate. Seems like exactly the kind of thing the Unicode Consortium is supposed to think through and avoid.
