### ISSUE TITLE
Any way to convert from string to codepoint?

### ISSUE THREAD

**Issue by dundargoc** [JuliaStrings/utf8proc#265]
I looked at the docs but couldn't find it. There is `utf8proc_encode_char` but that's the wrong direction, but there's not `utf8proc_decode_char` or similar. Does this functionality not exist or did I miss it? Thanks in advance.

(P.S. consider enabling Discussions for usage questions like this :) )

**Comment by stevengj** [comment]
`utf8proc_iterate`
