### ISSUE TITLE
Please make a new release with commit 3de4596

### ISSUE THREAD

**Issue by listout** [JuliaStrings/utf8proc#272]
On gentoo we don't use the bundled utf8proc that comes with neovim upstream. As a result we are getting build errors due to missing commit 3de4596. It would be great if you could make a new release with 3de4596

**Comment by clason** [comment]
https://github.com/JuliaStrings/utf8proc/pull/270#issuecomment-2321940335

Blocked by the corresponding PR; consider helping out if you can.

**Comment by tranquillity-codes** [comment]
@clason which corresponding PR ? #270 has been merged, no ?

**Comment by clason** [comment]
https://github.com/JuliaStrings/utf8proc/pull/271
