### ISSUE TITLE
non-deterministic Ruby-induced failures on Travis

### ISSUE THREAD

**Issue by stevengj** [JuliaStrings/utf8proc#52]
As seen in e.g #51 and #45, we are getting frequent Travis failures due to the Ruby data-generation script producing different results on Travis than on the machines where @jiahao and I generated the data.

It's not clear what is causing this.  If anyone can reproduce this failure locally, with any Ruby version, that would be helpful.  Try:

```
rm -f data/utf8proc_data.c.new
make data/utf8proc_data.c.new
diff utf8proc_data.c data/utf8proc_data.c.new
```

to see if the `diff` output is non-empty.

cc: @StefanKarpinski

**Comment by nalimilan** [comment]
`diff` is non-empty here on Fedora 22. Do you want me to try something?

**Comment by stevengj** [comment]
@nalimilan, I guess the next step would be getting a machine where `diff` is empty, and then the tedious grind of outputting intermediate results from earlier steps in the ruby script and seeing at what point a difference is introduced...

**Comment by stevengj** [comment]
This seems to no longer occur.
